mathjax:
  standalone: true
  html: >
    <!-- MathJax: Fall back to local if CDN offline but local image fonts are not 
    supported (saves >100MB) -->
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        tex2jax: {
          inlineMath: [['$','$'], ['\\(','\\)']],
          processEscapes: true
        }
      });
    </script>
    <script type='text/javascript'
    src='http://cdn.mathjax.org/mathjax/2.0-latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'>
    </script>
    {{^ page.mathjax.standalone }}
    <script>window.MathJax || document.write('<script type="text/x-mathjax-config">MathJax.Hub.Config({"HTML-CSS":{imageFont:null}});<\/script><script src="{{page.url.widgets}}/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML"><\/script>')
    </script>
    {{/ page.mathjax.standalone }}
